"""Settings module for test app."""

from app.models import SUPPORTED_MODELS

ENV = "development"
TESTING = True

SERVICE_API_KEY = "test-service-api-key"

ENABLE_AZURE = True
ENABLE_CODEX = True
ENABLE_ANTHROPIC = True

AZURE_BASE_URL = "https://test-resource.openai.azure.com"
AZURE_API_KEY = "test-api-key"
AZURE_MODEL_DEPLOYMENTS = {model: model for model in SUPPORTED_MODELS}
AZURE_SUMMARY_LEVEL = "detailed"
AZURE_VERBOSITY_LEVEL = "medium"
AZURE_TRUNCATION = "disabled"

RECORD_TRAFFIC = False
LOG_CONTEXT = True
LOG_COMPLETION = True
REASONING_DISPLAY_MODE = "mdthinkblocks"


AZURE_RESPONSES_API_URL = f"{AZURE_BASE_URL}/openai/v1/responses"

CODEX_AUTH_PATH = "~/.codex/auth.json"
CODEX_RESPONSES_URL = "https://chatgpt.com/backend-api/codex/responses"
CODEX_SUPPORTED_MODELS = ("codex-test-model", "codex-other-model")
CODEX_MODEL_REWRITES = {}
CODEX_ORIGINATOR = "codex_cli_rs"
CODEX_USER_AGENT = "test-agent"
CODEX_DISCOVERY_MODE = True
CODEX_TOKEN_REFRESH_SKEW_SECONDS = 300
CODEX_REQUEST_TIMEOUT_SECONDS = 600.0

ANTHROPIC_AUTH_PATH = "~/.conduit/anthropic_auth.json"
ANTHROPIC_BASE_URL = "https://api.anthropic.test"
ANTHROPIC_API_VERSION = "2023-06-01"
ANTHROPIC_SUPPORTED_MODELS = ("claude-opus-4-8", "claude-sonnet-4-6")
ANTHROPIC_MODEL_PROFILES = {}
ANTHROPIC_CACHE_CONTROL = "auto"
ANTHROPIC_CACHE_TTL = "5m"
ANTHROPIC_THINKING_DISPLAY = "summarized"
ANTHROPIC_EAGER_TOOL_STREAMING = True
ANTHROPIC_CLAUDE_CODE_VERSION = "2.1.75"
ANTHROPIC_TOKEN_REFRESH_SKEW_SECONDS = 300
ANTHROPIC_REQUEST_TIMEOUT_SECONDS = 600.0

FUSION_MODEL_PROFILES = {}
FUSION_PANEL_MAX_TOKENS = 256
FUSION_PANEL_TIMEOUT_SECONDS = 30.0
